const express=require('express'); const cors=require('cors'); const fs=require('fs'); const path=require('path'); const bcrypt=require('bcryptjs'); const jwt=require('jsonwebtoken');
const app=express(); app.use(cors()); app.use(express.json());
const DB=path.join(__dirname,'data','db.json'); const SECRET=process.env.JWT_SECRET||'troque-esta-chave-em-producao';
function load(){if(!fs.existsSync(DB)){fs.mkdirSync(path.dirname(DB),{recursive:true});fs.writeFileSync(DB,JSON.stringify({users:[],quotes:[],notifications:[]},null,2))} return JSON.parse(fs.readFileSync(DB));} function save(db){fs.writeFileSync(DB,JSON.stringify(db,null,2));}
function seed(){const db=load(); if(db.users.length)return; db.users=[{id:'u1',name:'Administrador',email:'admin@empresa.com',password:bcrypt.hashSync('123456',10),role:'admin',active:true},{id:'u2',name:'Compras',email:'compras@empresa.com',password:bcrypt.hashSync('123456',10),role:'compras',active:true},{id:'u3',name:'João',email:'vendedor1@empresa.com',password:bcrypt.hashSync('123456',10),role:'vendedor',active:true},{id:'u4',name:'Pedro',email:'vendedor2@empresa.com',password:bcrypt.hashSync('123456',10),role:'vendedor',active:true}]; save(db)} seed();
function auth(req,res,next){try{const t=(req.headers.authorization||'').replace('Bearer ',''); req.user=jwt.verify(t,SECRET); next()}catch(e){res.status(401).json({error:'Não autorizado'})}}
function can(...roles){return (req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Sem permissão'})}
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.post('/api/login',(req,res)=>{const db=load(); const u=db.users.find(x=>x.email.toLowerCase()===String(req.body.email||'').toLowerCase()&&x.active); if(!u||!bcrypt.compareSync(req.body.password||'',u.password))return res.status(401).json({error:'Email ou senha inválidos'}); const token=jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},SECRET,{expiresIn:'12h'}); res.json({token,user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/quotes',auth,(req,res)=>{const db=load(); let q=db.quotes.filter(x=>req.user.role==='vendedor'?x.sellerId===req.user.id:true); if(req.query.status)q=q.filter(x=>x.status===req.query.status); if(req.query.search){const s=req.query.search.toLowerCase();q=q.filter(x=>[x.code,x.brand,x.sellerName].some(v=>String(v).toLowerCase().includes(s)))} res.json({quotes:q.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))})});
app.post('/api/quotes',auth,can('vendedor'),(req,res)=>{const db=load(); const q={id:'q_'+Date.now(),sellerId:req.user.id,sellerName:req.user.name,code:String(req.body.code||'').trim(),brand:String(req.body.brand||'').trim(),quantity:Number(req.body.quantity||1),sellerObservation:String(req.body.observation||''),cash:null,credit:null,availability:null,purchaseObservation:'',status:'AGUARDANDO_COTACAO',createdAt:new Date().toISOString(),history:[],soldValue:null,saleObservation:''}; if(!q.code||!q.brand)return res.status(400).json({error:'Código e marca são obrigatórios'}); q.history.push({at:q.createdAt,user:req.user.name,action:'Criou a cotação',from:null,to:q.status}); db.quotes.push(q); notify(db,['u2','u1'],'Nova cotação',`${req.user.name} solicitou ${q.code} • ${q.brand}`,q.id); save(db); res.json({quote:q})});
function notify(db,ids,title,message,quoteId){ids.forEach(userId=>db.notifications.push({id:'n_'+Date.now()+'_'+Math.random(),userId,title,message,quoteId,read:false,createdAt:new Date().toISOString()}))}
app.put('/api/quotes/:id/quote',auth,can('compras','admin'),(req,res)=>{const db=load();const q=db.quotes.find(x=>x.id===req.params.id);if(!q)return res.status(404).json({error:'Cotação não encontrada'});q.cash=req.body.cash===''?null:Number(req.body.cash);q.credit=req.body.credit===''?null:Number(req.body.credit);q.availability=req.body.availability;q.purchaseObservation=req.body.observation||'';q.status='AGUARDANDO_DECISAO';q.quotedAt=new Date().toISOString();q.history.push({at:q.quotedAt,user:req.user.name,action:'Informou os preços',from:'AGUARDANDO_COTACAO',to:q.status});notify(db,[q.sellerId],'Cotação respondida',`Sua cotação ${q.code} foi respondida.`,q.id);save(db);res.json({quote:q})});
app.put('/api/quotes/:id/decision',auth,can('vendedor'),(req,res)=>{const db=load();const q=db.quotes.find(x=>x.id===req.params.id&&x.sellerId===req.user.id);if(!q)return res.status(404).json({error:'Cotação não encontrada'});const buy=Boolean(req.body.buy);q.status=buy?'PEDIDO':'NAO_PEDIDA';q.requestedAt=new Date().toISOString();q.history.push({at:q.requestedAt,user:req.user.name,action:buy?'Pediu a peça':'Não pediu a peça',from:'AGUARDANDO_DECISAO',to:q.status});notify(db,['u2','u1'],buy?'Peça solicitada':'Cotação recusada',`${req.user.name}: ${q.code} • ${q.brand}`,q.id);save(db);res.json({quote:q})});
app.put('/api/quotes/:id/result',auth,can('compras','admin'),(req,res)=>{const db=load();const q=db.quotes.find(x=>x.id===req.params.id);if(!q)return res.status(404).json({error:'Cotação não encontrada'});const sold=Boolean(req.body.sold);q.status=sold?'VENDIDA':'NAO_VENDIDA';q.soldValue=req.body.value===''?null:Number(req.body.value);q.saleObservation=req.body.observation||'';q.soldAt=new Date().toISOString();q.history.push({at:q.soldAt,user:req.user.name,action:sold?'Registrou venda':'Registrou não venda',from:'PEDIDO',to:q.status});notify(db,[q.sellerId],sold?'Venda registrada':'Resultado registrado',`${q.code}: ${sold?'vendida':'não vendida'}`,q.id);save(db);res.json({quote:q})});
app.get('/api/notifications',auth,(req,res)=>{const db=load();res.json({notifications:db.notifications.filter(n=>n.userId===req.user.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,50)})});
app.put('/api/notifications/read',auth,(req,res)=>{const db=load();db.notifications.filter(n=>n.userId===req.user.id).forEach(n=>n.read=true);save(db);res.json({ok:true})});
app.get('/api/stats',auth,can('compras','admin'),(req,res)=>{const db=load(),q=db.quotes;const total=q.length,aguardando=q.filter(x=>x.status==='AGUARDANDO_COTACAO').length,pedidos=q.filter(x=>x.status==='PEDIDO').length,vendas=q.filter(x=>x.status==='VENDIDA').length,valorVendido=q.reduce((s,x)=>s+(Number(x.soldValue)||0),0);const sellers=db.users.filter(u=>u.role==='vendedor');const ranking=sellers.map(u=>{const a=q.filter(x=>x.sellerId===u.id);return{seller:u.name,quotes:a.length,orders:a.filter(x=>x.status==='PEDIDO'||x.status==='VENDIDA'||x.status==='NAO_VENDIDA').length,sales:a.filter(x=>x.status==='VENDIDA').length,value:a.reduce((s,x)=>s+(Number(x.soldValue)||0),0)}});res.json({total,aguardando,pedidos,vendas,valorVendido,ranking})});
app.get('/api/users',auth,can('admin'),(req,res)=>{const db=load();res.json({users:db.users.map(({password,...u})=>u)})});
app.use(express.static(path.join(__dirname,'..','client','dist'))); app.get('*',(req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).end();res.sendFile(path.join(__dirname,'..','client','dist','index.html'))});
const PORT=process.env.PORT||3000; app.listen(PORT,()=>console.log(`CotaFácil online na porta ${PORT}`));
